### ISSUE TITLE
Animation looks broken on iOS 9.3?

### ISSUE THREAD

**Issue by benguild** [HarshilShah/DeckTransition#47]
I screenshotted this out of the Simulator. Haven't tested on a device yet.

![simulator screen shot - iphone 5s - 2017-11-12 at 11 15 32](https://user-images.githubusercontent.com/1185659/32695295-e2d022d4-c79a-11e7-912a-6d0c91c8021e.png)

**Comment by HarshilShah** [comment]
Hi there, thanks for filing an issue!

There was a bug in iOS where animating transforms for a view would sometimes make its subviews laid out with AutoLayout jump straight to the model values. This used to happen in some cases (the dismissal logic, for example, uses the same behaviour but the animation works perfectly there) but iOS 11 seems to have fixed the edge cases; meanwhile I adapted for iOS 11 but didn't noticed the regression in older OSes.

This has been fixed in v1.4.2
