### ISSUE TITLE
Bug on hidesBarsOnTap

### ISSUE THREAD

**Issue by Bronko44** [HarshilShah/DeckTransition#56]
Hello Harshil Shah! Thanks a lot of what are you doing!! 
In ios11 I found interesting bug. On hiding navigation bar on tap it disappears like on foto. Can you help with this? 

<img width="406" alt="screen shot 2017-12-19 at 7 53 49 pm" src="https://user-images.githubusercontent.com/17175251/34171278-6e0d2bbc-e4f6-11e7-8e1a-44b39c2b8dd1.png">
<img width="403" alt="screen shot 2017-12-19 at 7 54 03 pm" src="https://user-images.githubusercontent.com/17175251/34171279-6e2d16b6-e4f6-11e7-965d-537c56cbae66.png">

**Comment by Bronko44** [comment]
It works good on version 0.4, but now don't

**Comment by HarshilShah** [comment]
Sorry for the delay in the response.

I think I might have a solution here, but since I don't have access to your code I'm gonna need some help.

Could you let me know if adding `scrollViewUpdater = nil` right after this line here https://github.com/HarshilShah/DeckTransition/blob/master/Source/DeckPresentationController.swift#L583 solves the issue for you?

**Comment by Bronko44** [comment]
I use standard QuickLook library(QLPreviewController) to open files. And this QLPreviewController have default set  "hide bars on tap".  When I tap on image navigation bar disappears and  when I use your library this func 
 `@objc private func handlePan(gestureRecognizer: UIPanGestureRecognizer)` is not called at all.
  Unfortunately this line of code did not help.

**Comment by HarshilShah** [comment]
Hmm, interesting. Could you possibly upload a minimal demo project by modifying the example app to reproduce your issue?

**Comment by Bronko44** [comment]
Yeah sure, here is example: 
https://github.com/Bronko44/example

**Comment by HarshilShah** [comment]
Thank you so much for the example project!

So the issue here is that since navigation controllers are usually presented fullscreen, they just translate the bars directly with no clipping. Fortunately there's a simple solution for this.

In the DetailsVC's, if you use the following line, it will clip the navigation bar's contents:

```swift
navigationController?.view.clipsToBounds = true
```

Clipping has a performance cost sometimes, depending on exactly what drawing is going on, so I'd suggest toggling it with caution, but it does indeed make the animation look as you want it to.

**Comment by Bronko44** [comment]
Thanks a lot, this solved the problem. And thanks for a detailed explanation to, I appreciate it!
