### ISSUE TITLE
How can I get the percent complete of the present animation?

### ISSUE THREAD

**Issue by sashalondon** [HarshilShah/DeckTransition#57]
This is so I can alter the alpha of the dismiss icon. As the view presents it comes into view like the music app uses.

**Comment by HarshilShah** [comment]
So the percent complete isn't directly exposed here because the transition isn't interactive. However, you could use the `[presentAnimation](https://github.com/HarshilShah/DeckTransition/blob/master/Source/DeckTransitioningDelegate.swift#L59)` parameter in the `DeckTransitioningDelegate` to pass in a `dismissIcon.alpha = 1`, and that will be automatically animated alongside the present animation.

Hope this solves the issue for you.

**Comment by sashalondon** [comment]
Thank you I will try that.
