### ISSUE TITLE
Library causes lags in animations.

### ISSUE THREAD

**Issue by MehdiMahdloo** [HarshilShah/DeckTransition#59]
I'm currently working on an app using this great library, but there's seems to be a problem.
I have main screen, which has an "open" and "close" animation, which works fine.
After implementing Deck Transition and after opening several Deck Cards over my main screen, the animation I had before starts to lag.
If I remove Deck Transition from my project, the animations works great again.

So, might there be a memory problem in this library?
How can I solve the problem?

**Comment by jjjeeerrr111** [comment]
Unusable...tap tableviewcell and animation lags like 10 seconds before view controller is presented modally

**Comment by HarshilShah** [comment]
@MehdiMahdloo Because of certain UIKit issues there are a bunch of hacks in the library which take up extra memory. I've filed some radars regarding these, some of which have been resolved in Apple's own internal tooling but not released in public yet.

See #28 for example, which has been fixed in Apple Music as of iOS 11.2.5 (maybe earlier, but I'm not sure) but still remains an issue in iOS itself. The workaround uses snapshotting which adds some memory usage.

This builds up as you present more view controllers, and so until the radars are addressed, I'd recommend not stacking many cards. I'll admit this is not ideal, but my hands are really tied here, hope you can understand.

**Comment by HarshilShah** [comment]
@jjjeeerrr111 I haven't heard of your specific problem before. Do you mind filing a separate issue with more details and maybe a demo project?
