### ISSUE TITLE
Can't use scrollViewForDeck  for Outlet Views

### ISSUE THREAD

**Issue by rsekar1094** [HarshilShah/DeckTransition#72]
Crashing whenever returning a ScrollView which is added through storyBoard to the param **scrollViewForDeck**.(There is no issue when we add the scrollView through programmatically.)

The scrollViewForDeck param called before ViewDidLoad of presentedViewController which intends to crash with message "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value"

Code Snippet:

class TestViewController: UIViewController,DeckTransitionViewControllerProtocol {

    @IBOutlet weak var tableView: UITableView!
    
    var scrollViewForDeck : UIScrollView {
        get {
            return tableView
        }
    }

**Comment by HarshilShah** [comment]
Hi there, and thanks for opening an issue.

Could you please post an example project by modifying the Example app, with steps to repro? I cannot repro this bug myself.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsekharAppyog** [comment]
Hi @HarshilShah ,

Attached the sample project and screen shot where we are facing problem.
Please let me know if you want more details.


[Example.zip](https://github.com/HarshilShah/DeckTransition/files/2360227/Example.zip)

![screen shot 2018-09-05 at 1 41 20 pm](https://user-images.githubusercontent.com/38988176/45207550-df452a00-b2a5-11e8-883d-bd71487b514c.png)

**Comment by HarshilShah** [comment]
Could you please post an example which uses the current version of DeckTransition from the master branch? The example you've posted here references the properties `isSwipableSubViews` and `isSwipableScrollView` on the DeckTransitioningDelegate which are not part of my implementation, nor are they included in the example code.

**Comment by HarshilShah** [comment]
I'm not sure quite what's happening there (I don't use Storyboards much), but it seems like your table view isn't part of the view hierarchy The crash isn't happening because Deck is trying to access the table view before it's initialised; it's happening because the table view either never is initialised or is deallocated already.

The crash happens if you try to access the tableView in any way, not just when Deck does. This crashes too:

```swift
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    print(tableView.superview)
}
```

So the problem seems to be with your setup somewhere, not Deck
